
CFLAGS = -g -Wall
all :
	g++ $(CFLAGS) concreteclass.cpp -o concreteclass
	g++ $(CFLAGS) Date.cpp -o Date
	g++ $(CFLAGS) explicit.cpp -o explicit
	g++ $(CFLAGS) member.cpp -o member
	g++ $(CFLAGS) membertype.cpp -o membertype

clean :
	rm -rf *.o Date explicit member membertype concreteclass
